artifact_location: /Users/dj/Documents/GitHub/KeepCoding_Algorithm_Deployment/172.0.0.1:5000/0
creation_time: 1712507606769
experiment_id: '0'
last_update_time: 1712507606769
lifecycle_stage: active
name: Default
